// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/v1/reporting.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Usage struct {
	Product              string            `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Version              string            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Arch                 string            `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	Os                   string            `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Usage                map[string]string `protobuf:"bytes,5,rep,name=usage,proto3" json:"usage,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Usage) Reset()         { *m = Usage{} }
func (m *Usage) String() string { return proto.CompactTextString(m) }
func (*Usage) ProtoMessage()    {}
func (*Usage) Descriptor() ([]byte, []int) {
	return fileDescriptor_9df4dc8e97d3e9ee, []int{0}
}

func (m *Usage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Usage.Unmarshal(m, b)
}
func (m *Usage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Usage.Marshal(b, m, deterministic)
}
func (m *Usage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Usage.Merge(m, src)
}
func (m *Usage) XXX_Size() int {
	return xxx_messageInfo_Usage.Size(m)
}
func (m *Usage) XXX_DiscardUnknown() {
	xxx_messageInfo_Usage.DiscardUnknown(m)
}

var xxx_messageInfo_Usage proto.InternalMessageInfo

func (m *Usage) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func (m *Usage) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Usage) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

func (m *Usage) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *Usage) GetUsage() map[string]string {
	if m != nil {
		return m.Usage
	}
	return nil
}

type UsageResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsageResponse) Reset()         { *m = UsageResponse{} }
func (m *UsageResponse) String() string { return proto.CompactTextString(m) }
func (*UsageResponse) ProtoMessage()    {}
func (*UsageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9df4dc8e97d3e9ee, []int{1}
}

func (m *UsageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsageResponse.Unmarshal(m, b)
}
func (m *UsageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsageResponse.Marshal(b, m, deterministic)
}
func (m *UsageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsageResponse.Merge(m, src)
}
func (m *UsageResponse) XXX_Size() int {
	return xxx_messageInfo_UsageResponse.Size(m)
}
func (m *UsageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UsageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UsageResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Usage)(nil), "reportingapi.solo.io.Usage")
	proto.RegisterMapType((map[string]string)(nil), "reportingapi.solo.io.Usage.UsageEntry")
	proto.RegisterType((*UsageResponse)(nil), "reportingapi.solo.io.UsageResponse")
}

func init() { proto.RegisterFile("api/v1/reporting.proto", fileDescriptor_9df4dc8e97d3e9ee) }

var fileDescriptor_9df4dc8e97d3e9ee = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xcd, 0x26, 0x51, 0x9c, 0xa2, 0x96, 0xa5, 0xc8, 0x52, 0x2f, 0x25, 0x82, 0xf4, 0xb4,
	0xa5, 0xf5, 0x52, 0xc4, 0x93, 0xe0, 0x0f, 0x30, 0xe2, 0xc5, 0xdb, 0x1a, 0x87, 0xba, 0x58, 0x32,
	0xcb, 0x6e, 0xb2, 0xd0, 0x5f, 0xea, 0xdf, 0x91, 0xec, 0x26, 0x7a, 0x29, 0xb9, 0x0c, 0xf3, 0xde,
	0x63, 0x78, 0x1f, 0x03, 0xd7, 0xca, 0xe8, 0x95, 0x5f, 0xaf, 0x2c, 0x1a, 0xb2, 0x8d, 0xae, 0x77,
	0xd2, 0x58, 0x6a, 0x88, 0xcf, 0xfe, 0x0c, 0x65, 0xb4, 0x74, 0xb4, 0x27, 0xa9, 0xa9, 0xf8, 0x49,
	0x20, 0x7f, 0x73, 0x6a, 0x87, 0x5c, 0xc0, 0x99, 0xb1, 0xf4, 0xd9, 0x56, 0x8d, 0x48, 0x16, 0xc9,
	0xf2, 0xbc, 0x1c, 0x64, 0x97, 0x78, 0xb4, 0x4e, 0x53, 0x2d, 0x58, 0x4c, 0x7a, 0xc9, 0x39, 0x64,
	0xca, 0x56, 0x5f, 0x22, 0x0d, 0x76, 0xd8, 0xf9, 0x25, 0x30, 0x72, 0x22, 0x0b, 0x0e, 0x23, 0xc7,
	0x1f, 0x21, 0x6f, 0xbb, 0x02, 0x91, 0x2f, 0xd2, 0xe5, 0x64, 0x73, 0x27, 0x8f, 0x71, 0xc8, 0xc0,
	0x10, 0xe7, 0x73, 0xdd, 0xd8, 0x43, 0x19, 0x8f, 0xe6, 0x5b, 0x80, 0x7f, 0x93, 0x4f, 0x21, 0xfd,
	0xc6, 0x43, 0xcf, 0xd7, 0xad, 0x7c, 0x06, 0xb9, 0x57, 0xfb, 0x16, 0x7b, 0xb2, 0x28, 0x1e, 0xd8,
	0x36, 0x29, 0xae, 0xe0, 0x22, 0x5c, 0x96, 0xe8, 0x0c, 0xd5, 0x0e, 0x37, 0x08, 0xd3, 0x72, 0xa8,
	0x7e, 0x45, 0xeb, 0x75, 0x85, 0xfc, 0x05, 0x26, 0xd1, 0x8b, 0x3f, 0xb8, 0x19, 0x81, 0x9b, 0xdf,
	0x8e, 0x84, 0x43, 0x49, 0x71, 0xf2, 0x94, 0xbd, 0x33, 0xbf, 0xfe, 0x38, 0x0d, 0x4f, 0xbf, 0xff,
	0x0d, 0x00, 0x00, 0xff, 0xff, 0x74, 0x74, 0x59, 0x7d, 0x8e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReportingServiceClient is the client API for ReportingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReportingServiceClient interface {
	ReportUsage(ctx context.Context, in *Usage, opts ...grpc.CallOption) (*UsageResponse, error)
}

type reportingServiceClient struct {
	cc *grpc.ClientConn
}

func NewReportingServiceClient(cc *grpc.ClientConn) ReportingServiceClient {
	return &reportingServiceClient{cc}
}

func (c *reportingServiceClient) ReportUsage(ctx context.Context, in *Usage, opts ...grpc.CallOption) (*UsageResponse, error) {
	out := new(UsageResponse)
	err := c.cc.Invoke(ctx, "/reportingapi.solo.io.ReportingService/ReportUsage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportingServiceServer is the server API for ReportingService service.
type ReportingServiceServer interface {
	ReportUsage(context.Context, *Usage) (*UsageResponse, error)
}

// UnimplementedReportingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedReportingServiceServer struct {
}

func (*UnimplementedReportingServiceServer) ReportUsage(ctx context.Context, req *Usage) (*UsageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportUsage not implemented")
}

func RegisterReportingServiceServer(s *grpc.Server, srv ReportingServiceServer) {
	s.RegisterService(&_ReportingService_serviceDesc, srv)
}

func _ReportingService_ReportUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Usage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportingServiceServer).ReportUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reportingapi.solo.io.ReportingService/ReportUsage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportingServiceServer).ReportUsage(ctx, req.(*Usage))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReportingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "reportingapi.solo.io.ReportingService",
	HandlerType: (*ReportingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportUsage",
			Handler:    _ReportingService_ReportUsage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/reporting.proto",
}
